"""fix Role

Revision ID: 91e260d0fc4e
Revises: 076493af6cc0
Create Date: 2025-05-29 19:27:32.160078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e260d0fc4e'
down_revision: Union[str, None] = '076493af6cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_and_permissions', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles_and_permissions', 'is_deleted')
    # ### end Alembic commands ###
